#!/usr/bin/env python3
"""
Complete Identity Database Explorer

This script provides access to all 24k+ identities from the Anna Matrix.
Users can search, filter, and explore the complete dataset.
"""

import sys
import json
from pathlib import Path

# Add project root to Python path
project_root = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(project_root))

def load_database():
    """Load the complete mapping database."""
    # Try multiple possible locations
    possible_paths = [
        project_root / "outputs" / "analysis" / "complete_mapping_database.json",
        project_root / "complete_mapping_database.json",
        Path("outputs/analysis/complete_mapping_database.json"),
        Path("complete_mapping_database.json"),
        Path("data/complete_mapping_database.json"),
    ]
    
    db_path = None
    for path in possible_paths:
        if path.exists():
            db_path = path
            break
    
    if not db_path:
        print("ERROR: Database not found in any of these locations:")
        for path in possible_paths:
            print(f"  - {path}")
        print("\nPlease ensure the complete_mapping_database.json file exists.")
        print("It should be generated by the mapping scripts.")
        return None
    
    try:
        with open(db_path, 'r', encoding='utf-8') as f:
            db = json.load(f)
            print(f"Loaded database from: {db_path}")
            return db
    except Exception as e:
        print(f"ERROR: Failed to load database: {e}")
        return None

def display_statistics(db):
    """Display database statistics."""
    if not db:
        return
    
    # Try different possible structures
    stats = db.get('statistics', {})
    if not stats:
        # Try to calculate from mappings
        mappings = db.get('mappings', {})
        seed_to_real = mappings.get('seed_to_real_id', {})
        if seed_to_real:
            stats = {
                'total_identities': len(seed_to_real),
                'total_seeds': len(seed_to_real),
                'onchain_verified': len(seed_to_real),
                'match_rate': 0.0
            }
    
    print("\n" + "=" * 80)
    print("COMPLETE IDENTITY DATABASE - STATISTICS")
    print("=" * 80)
    print()
    print(f"Total Identities: {stats.get('total_identities', len(db.get('mappings', {}).get('seed_to_real_id', {})))}")
    print(f"Total Seeds: {stats.get('total_seeds', len(db.get('mappings', {}).get('seed_to_real_id', {})))}")
    print(f"On-Chain Verified: {stats.get('onchain_verified', 'All')}")
    print(f"Match Rate: {stats.get('match_rate', 0.0)}%")
    print()
    print("=" * 80)
    print()

def search_by_seed(db, seed):
    """Search for identities by seed."""
    if not db:
        return None
    
    mappings = db.get('mappings', {})
    seed_to_real = mappings.get('seed_to_real_id', {})
    seed_to_doc = mappings.get('seed_to_doc_id', {})
    
    # If structure is different, try direct access
    if not seed_to_real and 'seed_to_real_id' in db:
        seed_to_real = db['seed_to_real_id']
    if not seed_to_doc and 'seed_to_doc_id' in db:
        seed_to_doc = db['seed_to_doc_id']
    
    seed_lower = seed.lower().strip()
    
    if seed_lower in seed_to_real:
        doc_id = seed_to_doc.get(seed_lower, 'N/A') if seed_to_doc else 'N/A'
        return {
            'seed': seed_lower,
            'real_id': seed_to_real[seed_lower],
            'doc_id': doc_id,
            'match': seed_to_real[seed_lower] == doc_id if doc_id != 'N/A' else False
        }
    return None

def search_by_identity(db, identity):
    """Search for seed by identity."""
    if not db:
        return None
    
    mappings = db.get('mappings', {})
    real_to_seed = mappings.get('real_id_to_seed', {})
    doc_to_seed = mappings.get('doc_id_to_seed', {})
    
    # If structure is different, try direct access
    if not real_to_seed and 'real_id_to_seed' in db:
        real_to_seed = db['real_id_to_seed']
    if not doc_to_seed and 'doc_id_to_seed' in db:
        doc_to_seed = db['doc_id_to_seed']
    
    identity_upper = identity.upper().strip()
    
    if identity_upper in real_to_seed:
        return {
            'identity': identity_upper,
            'seed': real_to_seed[identity_upper],
            'type': 'real'
        }
    elif identity_upper in doc_to_seed:
        return {
            'identity': identity_upper,
            'seed': doc_to_seed[identity_upper],
            'type': 'documented'
        }
    return None

def display_sample_identities(db, count=10):
    """Display sample identities from the database."""
    if not db:
        return
    
    mappings = db.get('mappings', {})
    seed_to_real = mappings.get('seed_to_real_id', {})
    seed_to_doc = mappings.get('seed_to_doc_id', {})
    
    # If structure is different, try direct access
    if not seed_to_real and 'seed_to_real_id' in db:
        seed_to_real = db['seed_to_real_id']
    if not seed_to_doc and 'seed_to_doc_id' in db:
        seed_to_doc = db['seed_to_doc_id']
    
    if not seed_to_real:
        print("ERROR: Could not find seed_to_real_id mapping in database")
        print("Database structure may be different than expected.")
        return
    
    total = len(seed_to_real)
    display_count = min(count, total)
    
    print("\n" + "=" * 80)
    print(f"SAMPLE IDENTITIES (First {display_count} of {total})")
    print("=" * 80)
    print()
    
    for i, (seed, real_id) in enumerate(list(seed_to_real.items())[:display_count], 1):
        doc_id = seed_to_doc.get(seed, 'N/A') if seed_to_doc else 'N/A'
        match = "✓" if doc_id != 'N/A' and real_id == doc_id else "✗"
        
        print(f"{i}. Seed: {seed}")
        print(f"   Real ID:     {real_id}")
        if doc_id != 'N/A':
            print(f"   Documented:  {doc_id}")
            print(f"   Match:       {match}")
        print()
    
    print("=" * 80)
    print(f"For all {total} identities, use the search functions.")
    print("=" * 80)
    print()

def interactive_mode():
    """Interactive mode for exploring the database."""
    db = load_database()
    
    if not db:
        return
    
    display_statistics(db)
    display_sample_identities(db, 10)
    
    print("\n" + "=" * 80)
    print("INTERACTIVE MODE")
    print("=" * 80)
    print()
    print("Commands:")
    print("  search-seed <seed>     - Search by seed")
    print("  search-id <identity>    - Search by identity")
    print("  sample <count>         - Show sample identities")
    print("  stats                  - Show statistics")
    print("  quit                   - Exit")
    print()
    
    while True:
        try:
            cmd = input("> ").strip()
            
            if cmd == "quit" or cmd == "exit":
                break
            elif cmd == "stats":
                display_statistics(db)
            elif cmd.startswith("sample "):
                try:
                    count = int(cmd.split()[1])
                    display_sample_identities(db, count)
                except:
                    print("Usage: sample <count>")
            elif cmd.startswith("search-seed "):
                seed = cmd[12:].strip()
                result = search_by_seed(db, seed)
                if result:
                    print(f"\nSeed: {result['seed']}")
                    print(f"Real ID: {result['real_id']}")
                    print(f"Documented ID: {result['doc_id']}")
                    print(f"Match: {'Yes' if result['match'] else 'No'}")
                else:
                    print("Seed not found in database.")
            elif cmd.startswith("search-id "):
                identity = cmd[10:].strip()
                result = search_by_identity(db, identity)
                if result:
                    print(f"\nIdentity: {result['identity']}")
                    print(f"Seed: {result['seed']}")
                    print(f"Type: {result['type']}")
                else:
                    print("Identity not found in database.")
            else:
                print("Unknown command. Type 'quit' to exit.")
        except KeyboardInterrupt:
            print("\nExiting...")
            break
        except Exception as e:
            print(f"Error: {e}")

if __name__ == "__main__":
    if len(sys.argv) > 1:
        # Command-line mode
        db = load_database()
        if not db:
            sys.exit(1)
        
        if sys.argv[1] == "stats":
            display_statistics(db)
        elif sys.argv[1] == "sample":
            count = int(sys.argv[2]) if len(sys.argv) > 2 else 10
            display_sample_identities(db, count)
        elif sys.argv[1] == "search-seed" and len(sys.argv) > 2:
            result = search_by_seed(db, sys.argv[2])
            if result:
                print(json.dumps(result, indent=2))
            else:
                print("Seed not found")
        elif sys.argv[1] == "search-id" and len(sys.argv) > 2:
            result = search_by_identity(db, sys.argv[2])
            if result:
                print(json.dumps(result, indent=2))
            else:
                print("Identity not found")
        else:
            print("Usage:")
            print("  python explore_complete_database.py stats")
            print("  python explore_complete_database.py sample [count]")
            print("  python explore_complete_database.py search-seed <seed>")
            print("  python explore_complete_database.py search-id <identity>")
            print("  python explore_complete_database.py interactive")
    else:
        # Interactive mode
        interactive_mode()

